### ISSUE TITLE
Base openjdk image on Zulu

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/docker-openjdk#33]
https://github.com/zulu-openjdk/zulu-openjdk

f.e. `azul/zulu-openjdk-alpine:11.0.3-jre`

**Comment by JeroenKnoops** [comment]
@npalm Do you have an opinion about this?

**Comment by npalm** [comment]
@JeroenKnoops seems a good choice nowadays. @mpas what do you think?

**Comment by JeroenKnoops** [comment]
Zulu images are available now: https://github.com/philips-software/docker-openjdk#openjdk
